Troonch.Retail.App/Controllers/ItemsController.cs
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using Troonch.Application.Base.Utilities;
using Troonch.Domain.Base.DTOs.Response;
using Troonch.RetailSales.Product.Application.Services;
using Troonch.RetailSales.Product.Domain.DTOs.Requests;

namespace Troonch.Retail.App.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private readonly ILogger<ItemsController> _logger;
        private readonly ProductItemService _productItemService;
        private readonly ProductCategoryServices _productCategoryServices;
        private readonly ProductSizeOptionService _productSizeOptionService;
        public ItemsController(
            ILogger<ItemsController> logger,
            ProductItemService productItemService,
            ProductCategoryServices productCategoryServices,
            ProductSizeOptionService productSizeOptionService
            )
        {
            _logger = logger;
            _productItemService = productItemService;
            _productCategoryServices = productCategoryServices;
            _productSizeOptionService = productSizeOptionService;
        }


        [HttpGet("items/Index/{productId?}")]
        public async Task<IActionResult> Index(string? productId)
        {
            try
            {
                if(productId is null)
                {
                    throw new ArgumentNullException(productId);
                }

                var productItems = await _productItemService.GetProductItemsByProductIdAsync(Guid.Parse(productId));
                
                if(productItems is null)
                {
                    throw new ArgumentNullException($"product items list is null");
                }

                return PartialView("_Index", productItems);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ItemsController::RenderProductItemListByProductId -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ItemsController::RenderProductItemListByProductId -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }

        [HttpGet("GetProductItemsForm/{categoryId}/{productId}/{itemId?}")]
        public async Task<IActionResult> GetProductItemsForm(string categoryId,string productId, string? itemId)
        {
            var itemModel = new ProductItemRequestDTO();

            // Aggiungere il controllo sul productId
            itemModel.ProductId = Guid.Parse(productId);

            try
            {
                if (Guid.TryParse(categoryId,out Guid categoryIdParsed))
                {
                    await GetProductItemsBag(categoryIdParsed);
                }

                if (itemId is not null && Guid.TryParse(itemId, out Guid itemIdParsed))
                {
                    itemModel = await _productItemService.GetProductByIdForUpdateAsync(itemIdParsed);
                }


                return PartialView("_Form", itemModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductItemsController::GetProductItemsForm -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                var responseModel = new ResponseModel<bool>();
                _logger.LogError($"ProductItemsController::GetProductItemsForm -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }
        [HttpGet]
        public async Task<IActionResult> GenerateBarcode()
        {
            var responseModel = new ResponseModel<string>();
            try
            {
                var random = new Random();

                int[] barcodeDigits = new int[12];

                for (int i = 0; i < 12; i++)
                {
                    barcodeDigits[i] = random.Next(0, 10);
                }

                int sum = 0;
                for (int i = 0; i < 12; i++)
                {
                    int digit = barcodeDigits[i];
                    if (i % 2 == 0)
                    {
                        sum += digit;
                    }
                    else
                    {
                        sum += digit * 3;
                    }
                }
                int checkDigit = (10 - (sum % 10)) % 10;

                string barcode = string.Join("", barcodeDigits) + checkDigit;
                
                responseModel.Data = barcode;

                return StatusCode(200, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductItemsController::GenerateBarcode -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateItem([FromBody] ProductItemRequestDTO productItemModel)
        {
            var responseModel = new ResponseModel<bool>();

            try
            {
                var isProductAdded = await _productItemService.AddProductItemAsync(productItemModel);
                responseModel.Data = isProductAdded;

                if (!isProductAdded)
                {
                    throw new Exception();
                }


                return StatusCode(200, responseModel);
            }
            catch (ValidationException ex)
            {
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.ValidationErrors = FluentValidationUtility.SetValidationErrors(ex.Errors, _logger);
                responseModel.Error.Message = "Validation Error";
                return StatusCode(422, responseModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductItemsController::Create -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductItemsController::Create -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] ProductItemRequestDTO productItemModel)
        {
            var responseModel = new ResponseModel<bool>();

            try
            {

                var isProductUpdated = await _productItemService.UpdateProductItemAsync(productItemModel.Id ?? Guid.Empty, productItemModel);

                responseModel.Data = isProductUpdated;

                return StatusCode(200, responseModel);

            }
            catch (ValidationException ex)
            {
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.ValidationErrors = FluentValidationUtility.SetValidationErrors(ex.Errors, _logger);
                responseModel.Error.Message = "Validation Error";
                return StatusCode(422, responseModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductItemsController::Update -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Bad Request";
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductItemsController::Update -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }

        [HttpGet("items/Delete/{productItemId?}")]
        public async Task<IActionResult> Delete(string? productItemId)
        {
            var responseModel = new ResponseModel<bool>();
            try
            {
                if (Guid.TryParse(productItemId, out Guid productItemIdParsed))
                {
                    responseModel.Data = await _productItemService.DeleteProductItemByIdAsync(productItemIdParsed);
                    return StatusCode(200, responseModel);
                }
                else
                {
                    throw new Exception(nameof(productItemId));
                }
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductItemsController::Create -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();

Troonch.Retail.App/Controllers/ProductItemsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Troonch.Domain.Base.DTOs.Response;
using Troonch.RetailSales.Product.Application.Services;
using Troonch.RetailSales.Product.Domain.DTOs.Requests;

namespace Troonch.Retail.App.Controllers
{
    public class ProductItemsController : Controller
    {
        private readonly ILogger<ProductItemsController> _logger;
        private readonly ProductColorService _productColorService;
        private readonly ProductCategoryServices _productCategoryServices;
        private readonly ProductSizeOptionService _productSizeOptionService;
        public ProductItemsController(
            ILogger<ProductItemsController> logger,
            ProductColorService productColorService,
            ProductCategoryServices productCategoryServices,
            ProductSizeOptionService productSizeOptionService
            )
        {
            _logger = logger;
            _productColorService = productColorService;
            _productCategoryServices = productCategoryServices;
            _productSizeOptionService = productSizeOptionService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GetProductItemsForm/{categoryId}/{productId}/{itemId?}")]
        public async Task<IActionResult> GetProductItemsForm(string categoryId,string productId, string? itemId)
        {
            var itemModel = new ProductItemRequestDTO();

            // Aggiungere il controllo sul productId
            itemModel.ProductId = Guid.Parse(productId);

            try
            {
                await GetProductItemsBag(Guid.Parse(categoryId));
                
                return PartialView("_Form", itemModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductItemsController::GetProductItemsForm -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                var responseModel = new ResponseModel<bool>();
                _logger.LogError($"ProductItemsController::GetProductItemsForm -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }
        }

        [HttpGet("GenerateBarcode")]
        public async Task<IActionResult> GenerateBarcode()
        {
            var responseModel = new ResponseModel<string>();
            try
            {
                var random = new Random();

                int[] barcodeDigits = new int[12];

                for (int i = 0; i < 12; i++)
                {
                    barcodeDigits[i] = random.Next(0, 10);
                }

                int sum = 0;
                for (int i = 0; i < 12; i++)
                {
                    int digit = barcodeDigits[i];
                    if (i % 2 == 0)
                    {
                        sum += digit;
                    }
                    else
                    {
                        sum += digit * 3;
                    }
                }
                int checkDigit = (10 - (sum % 10)) % 10;

                string barcode = string.Join("", barcodeDigits) + checkDigit;
                
                responseModel.Data = barcode;

                //Check if is unique
                //var isUnique = await _product.IsBarcodeUnique(barcode);
                //if(!isUnique)
                //{
                //  GenerateBarcode();
                //}

                return StatusCode(200, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductItemsController::GenerateBarcode -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }
        }
        private async Task GetProductItemsBag(Guid categoryId)
        {
            var colors = await _productColorService.GetProductColorsAsync();

            if (colors is null)
            {
                throw new ArgumentNullException(nameof(colors));
            }

            ViewBag.Colors = colors;
            
            var category = await _productCategoryServices.GetProductCategoryByIdAsync(categoryId);

            if(category is null) 
            { 
                throw new ArgumentNullException(nameof(category));
            }

            var productSizeTypeId = category.ProductSizeTypeId;

            if(productSizeTypeId == Guid.Empty)
            {
                throw new Exception(nameof(productSizeTypeId));
            }

            var productSizeOptions = await _productSizeOptionService.GetProductSizeOptionsByTypeIdAsync(productSizeTypeId);

            ViewBag.SizeOptions = productSizeOptions;
        }
    }
}

Troonch.Retail.App/Views/Items/_Form.cshtml
@using System.Globalization;
@using Troonch.RetailSales.Product.Domain.DTOs.Requests;

@model ProductItemRequestDTO;

<div class="card-body">
    @using (Html.BeginForm("Create", "ProductItems", FormMethod.Post, new { @onsubmit = Model.Id == Guid.Empty ? $"submitProductItemsForm(event, \"{Url.Action("CreateItem", "Items")}\")" : $"submitProductItemsForm(event, \"{Url.Action("Update", "Items")}\")", @id = "product-item-form", @class = "forms-sample row" }))
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.Id, new {id="item-id"})
        @Html.HiddenFor(m => m.ProductId, new {id="product-id" ,data_error="productid"})

        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.ProductColor, "Colore")
            @Html.TextBoxFor(m => m.ProductColor, new { @class = "form-control", @id = "product-color"})
            @Html.ValidationMessageFor(m => m.ProductColor, "", new { @class = "text-danger mt-1 my-2 ms-1 d-block error-message", data_error = "productcolor" })
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.ProductSizeOptionId, "Taglia")
            @Html.DropDownListFor(m => m.ProductSizeOptionId, new SelectList(ViewBag.SizeOptions,"Id","Value"), new {@class="col-md-6 form-control",  @id="size"} )
            @Html.ValidationMessageFor(m => m.ProductSizeOptionId,"", new { @class="text-danger mt-1 my-2 ms-1 d-block error-message", data_error="productsizeoptionid"})
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(m => m.OriginalPrice, "Prezzo di Acquisto")
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-gradient-primary text-white">€</span>
                </div>
                @Html.TextBoxFor(m => m.OriginalPrice, new { @class="form-control", @id="original-price", @placeholder="0.00", type = "text", step = "0.01", min="0"})
            </div>
            @Html.ValidationMessageFor(m => m.OriginalPrice,"", new { @class="text-danger mt-1 my-2 ms-1 d-block error-message", data_error="originalprice"})
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(m => m.SalePrice, "Prezzo di Vendita")
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-gradient-primary text-white">€</span>
                </div>
                @Html.TextBoxFor(m => m.SalePrice, new { @class="form-control", @id="sale-price", @placeholder="0.00", type = "text", step = "0.01", min="0"})
            </div>
            @Html.ValidationMessageFor(m => m.SalePrice,"", new { @class="text-danger mt-1 my-2 ms-1 d-block error-message", data_error="saleprice"})
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(m => m.QuantityAvailable, "Quantità")
            @Html.TextBoxFor(m => m.QuantityAvailable, new { @class="form-control", @id="quantityAvailable", @placeholder="0", type = "number", step = "1", min="0"})
            @Html.ValidationMessageFor(m => m.QuantityAvailable,"", new { @class="text-danger mt-1 my-2 ms-1 d-block error-message", data_error="quantityavailable"})
        </div>

        <div class="form-group row justify-content-between align-items-center ">
            @Html.LabelFor(m => m.Barcode, "Barcode")
            <div class="col-8">
                @Html.TextBoxFor(m => m.Barcode, new { @class="form-control", @id="barcode", @placeholder="abc-123-asf", })
                @Html.ValidationMessageFor(m => m.Barcode,"", new { @class="text-danger mt-1 my-2 ms-1 d-block error-message", data_error="barcode"})
            </div>
            <div class="col-4">
                <button type="button" class="btn btn-info mb-2"  onclick="generateBarcode()">Genera Barcode</button>
            </div>
        </div>
        
        <div class="d-flex justify-content-end">
            <button type="button" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
        </div>
    }


</div>

Troonch.Retail.App/Views/Items/_Index.cshtml
@using Troonch.RetailSales.Product.Domain.DTOs.Responses;

@model List<ProductItemResponse>;

@if(Model.Any()){
    <table id="variations-table" class="table-hover w-100 d-none d-md-table mt-5">
        <thead>
            <tr>
                <th></th>
                <th>Colore</th>
                <th>Quantità</th>
                <th>Taglia</th>
                <th>Prezzo di Acquisto</th>
                <th>Prezzo di Vendita</th>
                <th>Barcode</th>
            </tr>
        </thead>
        <tbody class="overflow-y-section">
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        <div class="form-check form-check-primary">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" onclick="handleVariation(this)" value="@item.Id"><i class="input-helper"></i>
                            </label>
                        </div>
                    </td>
                    <td>@item.ColorName</td>
                    <td>@item.QuantityAvailable</td>
                    <td>@item.Size</td>
                    <td>@item.OriginalPrice @item.Currency</td>
                    <td>@item.SalePrice @item.Currency</td>
                    <td>@item.Barcode</td>
                </tr>
            }
        </tbody>
    </table>

    <ul id="variations-list" class="list-group d-block d-md-none overflow-y-section">
        @foreach (var item in Model)
        {
            <li class="list-group-item">
                <div class="row">
                    <div class="col-1">
                        <div class="form-check form-check-primary">
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" onclick="handleVariation(this)" value="@item.Id"><i class="input-helper"></i>
                            </label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row">
                            <div class="col-12"><strong>Colore:</strong> @item.ColorName</div>
                            <div class="col-12"><strong>Quantità:</strong> @item.QuantityAvailable</div>
                            <div class="col-12"><strong>Taglia:</strong> @item.Size</div>
                            <div class="col-12"><strong>Prezzo di Acquisto:</strong> @item.OriginalPrice @item.Currency</div>
                            <div class="col-12"><strong>Prezzo di Vendita:</strong> @item.SalePrice @item.Currency</div>
                            <div class="col-12"><strong>Barcode:</strong> @item.Barcode</div>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
}else{
    <div class="row overflow-y-section-700">
        <div class="col-md-12 grid-margin stretch-card ">
            <div class="card px-5 py-5 d-flex justify-content-center align-items-center">
                Nessuna Variazione disponibile al momento
            </div>
        </div>
    </div>
}