Troonch.Retail.App/Controllers/ProductsController.cs
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Troonch.Application.Base.Utilities;
using Troonch.Domain.Base.DTOs.Response;
using Troonch.Retail.App.Models;
using Troonch.RetailSales.Product.Application.Services;
using Troonch.RetailSales.Product.Domain.DTOs.Requests;
using Troonch.RetailSales.Product.Domain.DTOs.Responses;
using Troonch.Sales.Domain.Entities;

namespace Troonch.Retail.App.Controllers
{

    [Authorize]
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly ProductServices _productService;
        private readonly ProductBrandService _brandService;
        private readonly ProductCategoryServices _categoryService;
        private readonly ProductGenderService _productGenderService;
        private readonly ProductMaterialService _productMaterialService;
        private readonly ProductGenderCategoryService _productGenderCategoryService;

        [ActivatorUtilitiesConstructor]
        public ProductsController(
                                    ILogger<ProductsController> logger,
                                    ProductServices productService,
                                    ProductBrandService brandService,
                                    ProductCategoryServices categoryService,
                                    ProductGenderService productGenderService,
                                    ProductMaterialService productMaterialService,
                                    ProductGenderCategoryService productGenderCategoryService)
        {
            _logger = logger;
            _productService = productService;
            _brandService = brandService;
            _categoryService = categoryService;
            _productGenderService = productGenderService;
            _productMaterialService = productMaterialService;
            _productGenderCategoryService = productGenderCategoryService;
        }


        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string? searchTerm, [FromQuery] int page = 1, [FromQuery] int pagesize = 10)
        {
            try
            {
                var products = await _productService.GetProductsAsync(searchTerm);
                ViewData["Title"] = "Prodotti";
                return View(products);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductsController::Index -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductsController::Index -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }
        }

        [HttpGet("Products/Detail/{slug}")]
        public async Task<IActionResult> Detail(string slug)
        {
            try
            {
                var product = await _productService.GetProductBySlugAsync(slug);

                if(product is null)
                {
                    throw new ArgumentNullException(nameof(product));
                }

                return View(product);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductsController::Detail -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductsController::Detail -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }
        }

        [HttpGet("GetProductForm/{id?}")]
        public async Task<IActionResult> GetProductForm(string? id)
        {
            var productModel = new ProductRequestDTO();
            try
            {
                await GetProductBagForm();

                if (!String.IsNullOrEmpty(id))
                {
                    productModel = await _productService.GetProductByIdForUpdateAsync(Guid.Parse(id));
                    await InserCategorySelectedInViewBag(productModel.ProductCategoryId);
                }

                return PartialView("_Form", productModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductsController::GetProductForm -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductsController::GetProductForm -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
            
                var productModel = new ProductRequestDTO();
                await GetProductBagForm();

                return PartialView("_Form", productModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductsController::Create -> {ex.Message}");
                var responseModel = new ResponseModel<bool>();
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }

        }

        [HttpPost]
        public async Task<ActionResult<ResponseModel<bool>>> Create([FromBody] ProductRequestDTO productModel)
        {
            var responseModel = new ResponseModel<bool>();

            try
            {
                var isProductAdded = await _productService.AddProductAsync(productModel);

                responseModel.Data = isProductAdded;

                return StatusCode(200, responseModel);
            }
            catch (ValidationException ex)
            {
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.ValidationErrors = FluentValidationUtility.SetValidationErrors(ex.Errors, _logger);
                responseModel.Error.Message = "Validation Error";
                return StatusCode(422, responseModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"Api/ProductController::Create -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Api/ProductController::Create -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = ex.Message;
                return StatusCode(500, responseModel);
            }
        }

        

        [HttpPut]
        public async Task<ActionResult<ResponseModel<bool>>> Update([FromBody] ProductRequestDTO productModel)
        {
            var responseModel = new ResponseModel<bool>();

            try
            {

                var isProductUpdated = await _productService.UpdateProductAsync(productModel.Id ?? Guid.Empty, productModel);

                responseModel.Data = isProductUpdated;

                return StatusCode(200, responseModel);

            }
            catch (ValidationException ex)
            {
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.ValidationErrors = FluentValidationUtility.SetValidationErrors(ex.Errors, _logger);
                responseModel.Error.Message = "Validation Error";
                return StatusCode(422, responseModel);
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError($"ProductController::Update -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Bad Request";
                return StatusCode(400, responseModel);
            }
            catch (Exception ex)
            {
                _logger.LogError($"ProductController::Update -> {ex.Message}");
                responseModel.Status = ResponseStatus.Error.ToString();
                responseModel.Error.Message = "Internal Server Error";
                return StatusCode(500, responseModel);
            }
        }

        private async Task GetProductBagForm()
        {
            var brands = await _brandService.GetAllProductBrandAsync(null,1,10000);
            ViewBag.Brands = brands.Collections.OrderBy(b => b.Name);

            var categories = await _categoryService.GetProductCategoriesAsync(null,1, 10000);

Troonch.Retail.App/Controllers/UsersController.cs
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Troonch.Application.Base.Utilities;
using Troonch.User.Application.Services;
using Troonch.User.Domain.DTOs.Requests;

namespace Troonch.Retail.App.Controllers;

[Authorize]
public class UsersController : Controller
{
    private readonly ILogger<UsersController> _logger;
    private readonly UserService _userService;

    [ActivatorUtilitiesConstructor]
    public UsersController(
        ILogger<UsersController> logger,
        UserService userService
    )
    {
        _logger = logger;
        _userService = userService;
    }
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet("Users/Register/{id?}")]
    public async Task<IActionResult> Register(string? id)
    {
        var userRequest = new UserRequestDTO();
        
        try
        {

            if (!String.IsNullOrWhiteSpace(id))
            {
                userRequest = await _userService.GetUserByForUpdateAsync(id);
            }

            return View(userRequest);
        }
        catch (ArgumentNullException ex)
        {
            _logger.LogError($"UsersController::Register GET -> {ex.Message}");
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogError($"UsersController::Register GET -> {ex.Message}");
            throw;
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Register(UserRequestDTO request)
    {
        try
        {
            var identityResult = await _userService.RegisterUserAsync(request);

            if (!identityResult.Succeeded)
            {
                ModelState.SetModelState(identityResult.Errors, _logger);
                return View(identityResult.Errors);
            }

            return View("Index");
        }
        catch (ValidationException ex)
        {
            ModelState.SetModelState(ex.Errors, _logger);

            return View(request);
        }
        catch (ArgumentNullException ex)
        {
            _logger.LogError($"UsersController::Register POST-> {ex.Message}");
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogError($"UsersController::Register POST-> {ex.Message}");
            throw;
        }
    }
}

Troonch.Retail.App/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2024 @* <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a> *@. All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Troonch</span>
    </div>
</footer>

Troonch.Retail.App/Views/Shared/_Header.cshtml
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        <a class="navbar-brand brand-logo" href='@Url.Action("Index","Home")'><img src="~/assets/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href='@Url.Action("Index","Home")'><img src="~/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        @* <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                </div>
            </form>
        </div> *@
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-email-outline"></i>
                    <span class="count-symbol bg-warning"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-end navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <h6 class="p-3 mb-0">Messages</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="assets/images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
                            <p class="text-gray mb-0"> 1 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="assets/images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
                            <p class="text-gray mb-0"> 15 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/assets/images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
                            <p class="text-gray mb-0"> 18 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">4 new messages</h6>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-end navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <h6 class="p-3 mb-0">Notifications</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-success">
                                <i class="mdi mdi-calendar"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
                            <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-warning">
                                <i class="mdi mdi-cog"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
                            <p class="text-gray ellipsis mb-0"> Update dashboard </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-link-variant"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
                            <p class="text-gray ellipsis mb-0"> New admin wow! </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">See all notifications</h6>
                </div>
            </li>
            <partial name="_LoginPartial" />
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

Troonch.Retail.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Troonch Retail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Troonch.Retail.App.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <!----------------------------------->
    <div class="container-scroller">
        <!-- HEADER -->
        
        @{
            await Html.RenderPartialAsync("_Header");
        }
        <!-- CONTENT -->
        <div class="container-fluid page-body-wrapper">
            <!-- SIDE BAR -->
            @{
                await Html.RenderPartialAsync("_Sidebar");
            }
            <!-- MAIN -->
            <div class="main-panel">
                <!-- TOAST NOTIFICATION CONTAINER-->
                <div id="toast-container" class="toast-top-right"></div>
            
                <div class="content-wrapper">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @{
            await Html.RenderPartialAsync("_Footer");
        }
    </div>

    <div id="confirm-modal" class="modal fade" tabindex="-1" aria-labelledby="ConfirmModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="confirm-modal-title" class="modal-title"></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="confirm-modal-body" class="modal-body">
                    <p id="confirm-modal-answer"></p>

                    <div class="d-flex justify-content-end">
                        <button type="button" class="btn btn-sm btn-secondary mx-3" data-bs-dismiss="modal" aria-label="Close">
                            <i class="mdi mdi-close-circle mx-2"></i> Cancel
                        </button>
                        <button id="confirm-modal-button" type="button" class="btn btn-sm btn-primary" onclick="onClickConfirmUserModal(this)">
                            <i class="mdi mdi-checkbox-marked-circle mx-1"></i> Conferma
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!----------------------------------->
   
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/assets/vendors/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/jquery.cookie.js"></script>
    <script src="~/assets/js/dashboard.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="~/js/utilities.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Troonch.Retail.App/Views/Shared/_Notification.cshtml
@{
    string? message = null;

    if (TempData["message"] != null)
    {
        message = TempData["message"]?.ToString();
    }
}

@if (TempData["succeeded"] != null)
{
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            const isSucceeded = @TempData["succeeded"].ToString().ToLower();
            
            handleNotificationFromServer(isSucceeded, '@message');
        });
    </script>
}

Troonch.Retail.App/Views/Shared/_Pagination.cshtml
<nav aria-label="Page navigation" class="mt-2 me-2">
    <ul class="pagination justify-content-end">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link text-primary" onclick="pushToAnotherPage(this)" data-page="@(Model.Page - 1)" data-page-size="@Model.PageSize">Prev</a>
            </li>
        }

        @if (Model.HasPreviousPage || Model.HasNextPage)
        {
            @for (decimal i = 0; i < Model.TotalPages; i++)
            {
                @if (i + 1 == Model.Page)
                {
                    continue;
                }

                @if (!(i + 1 > Model.Page + 3) && !(i + 1 < Model.Page))
                {
                    <li class="page-item"><a class="page-link text-primary" onclick="pushToAnotherPage(this)" data-page="@(i + 1)" data-page-size="@Model.PageSize">@(i + 1)</a></li>
                }
            }
        }
        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a class="page-link text-primary" onclick="pushToAnotherPage(this)" data-page="@(Model.Page + 1)" data-page-size="@Model.PageSize">Succ</a>
            </li>
        }
    </ul>
</nav>


<script type="text/javascript">
    const pushToAnotherPage = (element) => {
        let searchTerm = document.getElementById('search-term').value;
        if (!searchTerm){
            searchTerm = "";
        }

        let page = element.getAttribute('data-page');

        if (!page) {
            page = "1";
        }

        let pageSize = element.getAttribute('data-page-size');

        if (!pageSize) {
            page = "10";
        }

        let controllerName = getControllerNameFromLocation();

        if (controllerName == null) {
            handleExceptionInFormWithRedirect(null);
        }

        window.location.href = '@Url.Action("Index", "__CONTROLLERNAME__")'.replace("__CONTROLLERNAME__", controllerName) +
            '?searchTerm=' + encodeURIComponent(searchTerm) +
            '&page=' + page +
            '&pagesize=' + pageSize;

    };
</script>

Troonch.Retail.App/Views/Shared/_SearchBar.cshtml
@{
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<div class="search-field d-none d-md-block ">
    @using (Html.BeginForm("Index", controllerName, FormMethod.Get, new { @onsubmit="keepTextSearched(event)",@id = "search-form", @class = "d-flex align-items-center h-100" }))
    {
        <div class="input-group">
            <button type="submit" class="input-group-prepend text-white bg-gradient-primary">
                <i class="mdi mdi-magnify"></i>
            </button>
            <input type="text" id="search-term" name="searchTerm" class="form-control border-0" placeholder="Cerca...">
        </div>
    }
</div>

<script type="text/javascript">

    document.addEventListener('DOMContentLoaded', () => {
        const searchTermStored = localStorage.getItem('searchTerm');
        if (searchTermStored == undefined || searchTermStored == null) {
            return;
        }

        document.getElementById('search-term').value = searchTermStored;
        
        localStorage.removeItem('searchTerm');
    })

    const keepTextSearched = (e) =>{
        e.preventDefault();

        const searchTerm = document.getElementById('search-term').value.trim();
        
        if (!searchTerm) {
            return e.target.submit();
        }
        
        document.getElementById('search-term').value = searchTerm;


        let searchTermStored = localStorage.getItem('searchTerm');
        if (searchTermStored != undefined && searchTerm != null) {
            localStorage.removeItem('searchTerm');
        }
        

        localStorage.setItem('searchTerm', searchTerm);

        e.target.submit();
    }
</script>

Troonch.Retail.App/Views/Shared/_Sidebar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/assets/images/faces/face1.jpg" alt="profile" />
                    <span class="login-status online"></span>    
                    <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                </div>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="collapse" href="#product-menu-item" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Prodotti</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi mdi-tshirt-crew menu-icon"></i>
            </a>
            <div class="collapse" id="product-menu-item">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">Lista</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Brands" asp-action="Index">Brands</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categorie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="pages/ui-features/buttons.html">Tag</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="collapse" href="#users-menu-item" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Utenti</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi mdi-account-circle menu-icon"></i>
            </a>
            <div class="collapse" id="users-menu-item">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Gestisci</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Register">Aggiungi Nuovo</a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</nav>